### ISSUE TITLE
Proper time and datetime edit support for some entities

### ISSUE THREAD

**Issue by ankohanse** [ankohanse/hass-studer-xcom#9]
RCC param 5002 (Date) has unit "Seconds" which represents seconds since 1 January 1970 at 00:00.
This results in values like '1731643811', which are not easily to verify or to enter.
Home Assistant provides entity platform DateTime which should present the value as a proper date and time edit field.

XT param 1206 (Start hour AUX1), 1207 (End hour AUX1) and several similar others have unit "Minutes" which represents minutes since midnight, 0=00:00 to 1440=24:00.
Home Assistant provides entity platform Time which should present the value as a proper time edit field.

**Comment by ankohanse** [comment]
Implemented in release v2024.11.2.

This change allows to create an automation that will periodically correct the Studer system time. This is needed for some (off-grid) system, where the time slowly shifts byabout 1 minute per month.
Below is an example for such an automation:
```
alias: Studer RCC Sync Time
description: ""
triggers:
  - trigger: time_pattern
    hours: "0"
    minutes: "0"
    seconds: "0"
conditions: []
actions:
  - action: datetime.set_value
    metadata: {}
    data:
      datetime: "{{ now() }}"
    target:
      entity_id: datetime.studer_4001_rcc_5002
mode: single
```
